name: Notify espd-tools to update ESPD_CM.eapx

on:
  push:
    branches:
      - testingAutomation

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Create Github App Installation token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: OP-TED
          repositories: espd-tools

      - name: Debug App installation
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -s -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
                https://api.github.com/user/installations | jq

      - name: Send repository dispatch to espd-tools
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Triggering repository_dispatch in espd-tools..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
              https://api.github.com/repos/OP-TED/espd-tools/dispatches \
            -d '{"event_type": "update_eapx"}'
