name: Extract and update JSON in espd-tools

on:
  push:
    branches:
      - testingAutomation

jobs:
  extract-and-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout this repository (espd-conceptual-model)
      - name: Checkout conceptual model
        uses: actions/checkout@v4
        with:
          path: conceptual-model

      # Checkout the target repository (espd-tools) and target branch
      - name: Checkout espd-tools
        uses: actions/checkout@v4
        with:
          repository: OP-TED/espd-tools
          ref: testingAutomation
          path:  espd-tools
          token: ${{ secrets.TOOLS_PUSH_TOKEN }}

      # Checkout the target repository (espd-demo repo) and target branch
      - name: Checkout espd-demo
        uses: actions/checkout@v4
        with:
          repository: OP-TED/espd-demo
          ref: testingAutomation
          path: espd-demo
          token: ${{ secrets.TOOLS_PUSH_TOKEN }}

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Run your extraction script from conceptual-model repo
      - name: Extract files
        working-directory: espd-tools/EAtoJSON
        run: |
          npm ci
          node export.js all -o ../../conceptual-model/conceptual-model/ESPD_CM.eapx
          echo "Extraction completed."

      # Commit and push changes to espd-tools
      - name: Commit and push to espd-tools
        working-directory: espd-tools
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add EAtoJSON/ESPD_CM.json
            git commit -m "Auto-update ESPD_CM.json from conceptual-model"
            git push origin testingAutomation
          else
            echo "No changes to commit"
          fi

      # # Copy ESPD_CM.json into espd-demo/ESPD/model/
      # - name: Copy JSON into espd-demo
      #   run: |
      #     mkdir -p espd-demo/ESPD/model
      #     cp espd-tools/EAtoJSON/ESPD_CM.json espd-demo/ESPD/model/ESPD_CM.json
      #     echo "Copied ESPD_CM.json into espd-demo/ESPD/model"

      # # Commit and push to espd-demo
      # - name: Commit and push to espd-demo
      #   working-directory: espd-demo
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     if [[ `git status --porcelain` ]]; then
      #       git add ESPD/model/ESPD_CM.json
      #       git commit -m "Auto-update ESPD_CM.json from espd-tools"
      #       git push origin testingAutomation
      #     else
      #       echo "No changes to commit in espd-demo"
      #     fi
